### PR TITLE
Update to work with current wrangler

### PR DESCRIPTION
**Pull request by s-crypt**
Thanks for your great wrangler script! It works great, I have added a few changes and fixes to update everything to the current version and compatibility.
I have also made some changes to the default config as I think it would be more applicable to people who just want to upload and forget it. All the changes have comments in the github diff.

### CODE REVIEW

**Comment by Ergberg** [comment]
Hello @s-crypt! Thank you so much for sharing this!
I'm glad it works for you and that you find the script useful
I'll be happy to merge the changes of course ;-)

**Comment by Ergberg** [comment]
Just saw that this project never made it to npm. How did you find it? Just searching github?

**Comment by s-crypt** [comment]
Actually, this project repo was the third result when searching DuckDuckGo for "[auto delete cloudflare pages deployments](https://duckduckgo.com/?t=ffab&q=auto+delete+old+cloudflare+pages+deployments&ia=web)"!

**Comment by Ergberg** [comment]
Haha, great! 
Again, thanks a lot!

**Pull request merged**
